### ISSUE TITLE
Have you used kmeans clustering on wider face dataset

### ISSUE THREAD

**Issue by look4pritam** [ltkhang/face-detection-yolov4-tiny#1]
Have you used kmeans clustering on wider face dataset to get anchor boxes?

**Comment by ltkhang** [comment]
> Have you used kmeans clustering on wider face dataset to get anchor boxes?

Sorry for the late response. No, I used the default anchor settings, because I found that analyzing the dataset (with darknet) to get a new anchor can boost the IoU in the validation set but getting worse accuracy in the real environment.

**Comment by look4pritam** [comment]
Thank you.
